#!/usr/bin/env python
from panflute import toJSONFilter, Cite
from sys import stderr

def action(elem, doc):
    if isinstance(elem, Cite):
        print(elem, file=stderr)
    return None

if __name__ == '__main__':
    toJSONFilter(action)