name: Docker container builder 
on:
  push:
    branches:
      - master
jobs:
  build_test:
    # Note: for deployment, we move to an older version of Ubuntu
    # https://pyinstaller.readthedocs.io/en/stable/usage.html
    runs-on: ubuntu-18.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Update submodules
        run: git submodule update --init --recursive

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: backend_meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/davenquinn/paper-engine
          tags: |
            type=match,pattern=v(.*),group=1
            type=pep440,pattern={{version}}
      - name: Build and push backend
        uses: docker/build-push-action@v2
        with:
          context: backend
          push: true
          tags: ${{ steps.backend_meta.outputs.tags }}
          labels: ${{ steps.backend_meta.outputs.labels }}
          cache-from: type=registry,ref=ghcr.io/davenquinn/paper-engine:latest
          cache-to: type=inline